version: '3.3'
services:
  web:
    image: teracy/angular-cli:latest
    ports:
      - 5555:4200
    volumes:
      - .:/opt/app/
    stdin_open: true
    tty: true
    working_dir: /opt/app/paperbits-angular
    command: bash -c "yarn install && ng serve --host 0.0.0.0"
